import { isPronounceSimilarlySpanish } from "./pronounciation";

describe("isPronounceSimilarlySpanish", () => {
  it("should classify correctly", () => {
    const result = names.map((name) => {
      return {
        ...name,
        similar: isPronounceSimilarlySpanish(name.name, name.pronounciation),
      };
    });
    expect(result).toEqual(names);
  });
});

const names = [
  { name: "Fabio", pronounciation: "f aa1 b iy0 ow0", similar: true },
  { name: "John", pronounciation: "jh aa1 n", similar: false },
  { name: "William", pronounciation: "w ih1 l y ah0 m", similar: false },
  { name: "Mary", pronounciation: "m eh1 r iy0", similar: false },
  { name: "James", pronounciation: "jh ey1 m z", similar: false },
  { name: "Charles", pronounciation: "ch aa1 r l z", similar: false },
  { name: "George", pronounciation: "jh ao1 r jh", similar: false },
  { name: "Frank", pronounciation: "f r ae1 ng k", similar: true },
  { name: "Joseph", pronounciation: "jh ow1 s ah0 f", similar: false },
  { name: "Anna", pronounciation: "ae1 n ah0", similar: true },
  { name: "Thomas", pronounciation: "t aa1 m ah0 s", similar: false },
  { name: "Henry", pronounciation: "hh eh1 n r iy0", similar: false },
  { name: "Robert", pronounciation: "r aa1 b er0 t", similar: true },
  { name: "Edward", pronounciation: "eh1 d w er0 d", similar: true },
  { name: "Harry", pronounciation: "hh eh1 r iy0", similar: false },
  { name: "Emma", pronounciation: "eh1 m ah0", similar: true },
  { name: "Elizabeth", pronounciation: "ih0 l ih1 z ah0 b ah0 th", similar: true },
  { name: "Walter", pronounciation: "w ao1 l t er0", similar: true },
  { name: "Minnie", pronounciation: "m ih1 n iy0", similar: false },
  { name: "Arthur", pronounciation: "aa1 r th er0", similar: false },
  { name: "Margaret", pronounciation: "m aa1 r g er0 ih0 t", similar: false },
  { name: "Fred", pronounciation: "f r eh1 d", similar: true },
  { name: "Albert", pronounciation: "ae1 l b er0 t", similar: true },
  { name: "Ida", pronounciation: "ay1 d ah0", similar: false },
  { name: "Alice", pronounciation: "ae1 l ih0 s", similar: false },
  { name: "Bertha", pronounciation: "b er1 th ah0", similar: false },
  { name: "Sarah", pronounciation: "s eh1 r ah0", similar: false },
  { name: "Annie", pronounciation: "ae1 n iy0", similar: false },
  { name: "Clara", pronounciation: "k l ae1 r ah0", similar: false },
  { name: "Ella", pronounciation: "eh1 l ah0", similar: true },
  { name: "Florence", pronounciation: "f l ao1 r ah0 n s", similar: false },
  { name: "Cora", pronounciation: "k ao1 r ah0", similar: true },
  { name: "Martha", pronounciation: "m aa1 r th ah0", similar: false },
  { name: "Samuel", pronounciation: "s ae1 m y uw0 l", similar: false },
  { name: "Laura", pronounciation: "l ao1 r ah0", similar: false },
  { name: "Nellie", pronounciation: "n eh1 l iy0", similar: false },
  { name: "Grace", pronounciation: "g r ey1 s", similar: false },
  { name: "Carrie", pronounciation: "k eh1 r iy0", similar: false },
  { name: "David", pronounciation: "d ey1 v ih0 d", similar: false },
  { name: "Maude", pronounciation: "m ao1 d", similar: false },
  { name: "Louis", pronounciation: "l uw1 ih0 s", similar: false },
  { name: "Mabel", pronounciation: "m ey1 b ah0 l", similar: false },
  { name: "Bessie", pronounciation: "b eh1 s iy0", similar: false },
  { name: "Jennie", pronounciation: "jh eh1 n iy0", similar: false },
  { name: "Gertrude", pronounciation: "g er1 t r uw0 d", similar: false },
  { name: "Julia", pronounciation: "jh uw1 l y ah0", similar: false },
  { name: "Hattie", pronounciation: "hh ae1 t iy0", similar: false },
  { name: "Edith", pronounciation: "iy1 d ih0 th", similar: false },
  { name: "Joe", pronounciation: "jh ow1", similar: false },
  { name: "Charlie", pronounciation: "ch aa1 r l iy0", similar: false },
  { name: "Clarence", pronounciation: "k l eh1 r ah0 n s", similar: false },
  { name: "Richard", pronounciation: "r ih1 ch er0 d", similar: false },
  { name: "Mattie", pronounciation: "m ae1 t iy0", similar: false },
  { name: "Rose", pronounciation: "r ow1 z", similar: false },
  { name: "Catherine", pronounciation: "k ae1 th er0 ah0 n", similar: false },
  { name: "Lillian", pronounciation: "l ih1 l iy0 ah0 n", similar: true },
  { name: "Ada", pronounciation: "ey1 d ah0", similar: false },
  { name: "Lillie", pronounciation: "l ih1 l iy0", similar: false },
  { name: "Andrew", pronounciation: "ae1 n d r uw0", similar: false },
  { name: "Daniel", pronounciation: "d ae1 n y ah0 l", similar: true },
  { name: "Helen", pronounciation: "hh eh1 l ah0 n", similar: true },
  { name: "Jessie", pronounciation: "jh eh1 s iy0", similar: false },
  { name: "Louise", pronounciation: "l uw0 iy1 z", similar: false },
  { name: "Ethel", pronounciation: "eh1 th ah0 l", similar: false },
  { name: "Lula", pronounciation: "l uw1 l ah0", similar: true },
  { name: "Myrtle", pronounciation: "m er1 t ah0 l", similar: false },
  { name: "Ernest", pronounciation: "er1 n ah0 s t", similar: true },
  { name: "Eva", pronounciation: "ey1 v ah0", similar: true },
  { name: "Frances", pronounciation: "f r ae1 n s ih0 s", similar: false },
  { name: "Lena", pronounciation: "l iy1 n ah0", similar: false },
  { name: "Lucy", pronounciation: "l uw1 s iy0", similar: false },
  { name: "Edna", pronounciation: "eh1 d n ah0", similar: true },
  { name: "Will", pronounciation: "w ih1 l", similar: true },
  { name: "Maggie", pronounciation: "m ae1 g iy2", similar: false },
  { name: "Pearl", pronounciation: "p er1 l", similar: false },
  { name: "Jesse", pronounciation: "jh eh1 s iy0", similar: false },
  { name: "Daisy", pronounciation: "d ey1 z iy0", similar: false },
  { name: "Fannie", pronounciation: "f ae1 n iy0", similar: false },
  { name: "Josephine", pronounciation: "jh ow1 s ah0 f iy2 n", similar: false },
  { name: "Oscar", pronounciation: "ao1 s k er0", similar: true },
  { name: "Dora", pronounciation: "d ao1 r ah0", similar: true },
  { name: "Lewis", pronounciation: "l uw1 ih0 s", similar: false },
  { name: "Rosa", pronounciation: "r ow1 z ah0", similar: true },
  { name: "Katherine", pronounciation: "k ae1 th er0 ih0 n", similar: false },
  { name: "Peter", pronounciation: "p iy1 t er0", similar: false },
  { name: "Benjamin", pronounciation: "b eh1 n jh ah0 m ah0 n", similar: false },
  { name: "Frederick", pronounciation: "f r eh1 d r ih0 k", similar: false },
  { name: "Willie", pronounciation: "w ih1 l iy0", similar: false },
  { name: "Agnes", pronounciation: "ae1 g n ih0 s", similar: false },
  { name: "Marie", pronounciation: "m er0 iy1", similar: false },
  { name: "Nora", pronounciation: "n ao1 r ah0", similar: true },
  { name: "Alfred", pronounciation: "ae1 l f r ih0 d", similar: true },
  { name: "May", pronounciation: "m ey1", similar: false },
  { name: "Sam", pronounciation: "s ae1 m", similar: true },
  { name: "Roy", pronounciation: "r oy1", similar: true },
  { name: "Mamie", pronounciation: "m ey1 m iy0", similar: false },
];
